/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetingIndexRouteImport } from './routes/meeting/index'
import { Route as ScheduleShareRouteImport } from './routes/schedule/share'
import { Route as ScheduleCalendarRouteImport } from './routes/schedule/calendar'
import { Route as MeetingJoinRouteImport } from './routes/meeting/join'
import { Route as MeetingCreateRouteImport } from './routes/meeting/create'
import { Route as MeetingInviteCodeRouteImport } from './routes/meeting/$inviteCode'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ScheduleViewUidIdRouteImport } from './routes/schedule/view/$uid/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingIndexRoute = MeetingIndexRouteImport.update({
  id: '/meeting/',
  path: '/meeting/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleShareRoute = ScheduleShareRouteImport.update({
  id: '/schedule/share',
  path: '/schedule/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleCalendarRoute = ScheduleCalendarRouteImport.update({
  id: '/schedule/calendar',
  path: '/schedule/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingJoinRoute = MeetingJoinRouteImport.update({
  id: '/meeting/join',
  path: '/meeting/join',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingCreateRoute = MeetingCreateRouteImport.update({
  id: '/meeting/create',
  path: '/meeting/create',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingInviteCodeRoute = MeetingInviteCodeRouteImport.update({
  id: '/meeting/$inviteCode',
  path: '/meeting/$inviteCode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleViewUidIdRoute = ScheduleViewUidIdRouteImport.update({
  id: '/schedule/view/$uid/$id',
  path: '/schedule/view/$uid/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/meeting/$inviteCode': typeof MeetingInviteCodeRoute
  '/meeting/create': typeof MeetingCreateRoute
  '/meeting/join': typeof MeetingJoinRoute
  '/schedule/calendar': typeof ScheduleCalendarRoute
  '/schedule/share': typeof ScheduleShareRoute
  '/meeting': typeof MeetingIndexRoute
  '/schedule/view/$uid/$id': typeof ScheduleViewUidIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/meeting/$inviteCode': typeof MeetingInviteCodeRoute
  '/meeting/create': typeof MeetingCreateRoute
  '/meeting/join': typeof MeetingJoinRoute
  '/schedule/calendar': typeof ScheduleCalendarRoute
  '/schedule/share': typeof ScheduleShareRoute
  '/meeting': typeof MeetingIndexRoute
  '/schedule/view/$uid/$id': typeof ScheduleViewUidIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/meeting/$inviteCode': typeof MeetingInviteCodeRoute
  '/meeting/create': typeof MeetingCreateRoute
  '/meeting/join': typeof MeetingJoinRoute
  '/schedule/calendar': typeof ScheduleCalendarRoute
  '/schedule/share': typeof ScheduleShareRoute
  '/meeting/': typeof MeetingIndexRoute
  '/schedule/view/$uid/$id': typeof ScheduleViewUidIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/login'
    | '/meeting/$inviteCode'
    | '/meeting/create'
    | '/meeting/join'
    | '/schedule/calendar'
    | '/schedule/share'
    | '/meeting'
    | '/schedule/view/$uid/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/login'
    | '/meeting/$inviteCode'
    | '/meeting/create'
    | '/meeting/join'
    | '/schedule/calendar'
    | '/schedule/share'
    | '/meeting'
    | '/schedule/view/$uid/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/auth/login'
    | '/meeting/$inviteCode'
    | '/meeting/create'
    | '/meeting/join'
    | '/schedule/calendar'
    | '/schedule/share'
    | '/meeting/'
    | '/schedule/view/$uid/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  MeetingInviteCodeRoute: typeof MeetingInviteCodeRoute
  MeetingCreateRoute: typeof MeetingCreateRoute
  MeetingJoinRoute: typeof MeetingJoinRoute
  ScheduleCalendarRoute: typeof ScheduleCalendarRoute
  ScheduleShareRoute: typeof ScheduleShareRoute
  MeetingIndexRoute: typeof MeetingIndexRoute
  ScheduleViewUidIdRoute: typeof ScheduleViewUidIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/': {
      id: '/meeting/'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/share': {
      id: '/schedule/share'
      path: '/schedule/share'
      fullPath: '/schedule/share'
      preLoaderRoute: typeof ScheduleShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/calendar': {
      id: '/schedule/calendar'
      path: '/schedule/calendar'
      fullPath: '/schedule/calendar'
      preLoaderRoute: typeof ScheduleCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/join': {
      id: '/meeting/join'
      path: '/meeting/join'
      fullPath: '/meeting/join'
      preLoaderRoute: typeof MeetingJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/create': {
      id: '/meeting/create'
      path: '/meeting/create'
      fullPath: '/meeting/create'
      preLoaderRoute: typeof MeetingCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/$inviteCode': {
      id: '/meeting/$inviteCode'
      path: '/meeting/$inviteCode'
      fullPath: '/meeting/$inviteCode'
      preLoaderRoute: typeof MeetingInviteCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/view/$uid/$id': {
      id: '/schedule/view/$uid/$id'
      path: '/schedule/view/$uid/$id'
      fullPath: '/schedule/view/$uid/$id'
      preLoaderRoute: typeof ScheduleViewUidIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  MeetingInviteCodeRoute: MeetingInviteCodeRoute,
  MeetingCreateRoute: MeetingCreateRoute,
  MeetingJoinRoute: MeetingJoinRoute,
  ScheduleCalendarRoute: ScheduleCalendarRoute,
  ScheduleShareRoute: ScheduleShareRoute,
  MeetingIndexRoute: MeetingIndexRoute,
  ScheduleViewUidIdRoute: ScheduleViewUidIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
